In [1]:
import cv2

In [2]:
import numpy as np


In [3]:
cap = cv2.VideoCapture('bolt_test_pothole.mp4')

In [4]:
while(True):
  # Capture frame-by-frame
    ret, frame = cap.read()

   # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray,(5,5),0)
    ret, thresh_img = cv2.threshold(blur,91,255,cv2.THRESH_BINARY)
   #Finding Contours
    contours =  cv2.findContours(thresh_img,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)[-2]
    
    for c in contours:
        mask = np.zeros(c.shape[:2],np.uint8)
        mean = cv2.mean(c,mask)
        
        area = cv2.contourArea(c)
        #Applying area condition to remove very small and big contours
        if area>300.0 and area<1500.0:
      
         x,y,w,h = cv2.boundingRect(c)
         col_arr = np.array(cv2.mean(frame[y:y+h,x:x+w])).astype(np.uint8)
         print(col_arr)
         #Applying condition to remove contours having other colours than white
         if col_arr[0]>100 and col_arr[1]>100:
            #removing rectangles that are too wide for a pothole
            if h<100 and w<100 and w>h:
               cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
        
     # Display the resulting frame
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

[117 120 131   0]
[ 75  90 113   0]
[68 80 99  0]
[118 120 131   0]
[ 75  90 113   0]
[68 80 99  0]
[118 121 131   0]
[ 75  90 114   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 114   0]
[67 80 98  0]
[118 121 131   0]
[ 75  90 114   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 114   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 114   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[118 121 131   0]
[ 74  90 113   0]
[67 80 98  0]
[118 121 131   0]
[ 74  90 113   0]
[67 80 98  0]
[118 121 131   0]
[ 75  90 113   0]
[67 80 98  0]
[119 121 132   0]
[ 75  90 113   0]
[67 80 99  0]
[119 121 131   0]
[ 75  90 113   0]
[67 80 99  0]
[119 121 132   0]
[ 75  90 113   0]
[67 80 98  0]


[118 120 132   0]
[ 74  93 112   0]
[67 80 97  0]
[123 123 131   0]
[120 121 131   0]
[122 123 131   0]
[120 121 133   0]
[ 73  92 111   0]
[68 81 98  0]
[116 118 132   0]
[119 120 130   0]
[114 118 133   0]
[121 122 133   0]
[ 73  92 111   0]
[68 81 98  0]
[116 118 131   0]
[121 121 130   0]
[112 117 133   0]
[116 119 132   0]
[119 121 131   0]
[ 71  91 110   0]
[67 81 97  0]
[116 119 130   0]
[121 122 131   0]
[115 119 131   0]
[118 120 132   0]
[ 72  92 111   0]
[68 81 97  0]
[122 123 134   0]
[121 121 131   0]
[108 114 130   0]
[115 118 131   0]
[113 118 131   0]
[ 71  91 111   0]
[68 81 97  0]
[123 124 133   0]
[122 122 131   0]
[116 119 130   0]
[117 119 131   0]
[121 122 133   0]
[ 72  90 111   0]
[68 81 97  0]
[124 124 133   0]
[123 124 133   0]
[109 116 132   0]
[117 120 132   0]
[120 122 132   0]
[ 72  92 111   0]
[67 80 97  0]
[124 125 133   0]
[121 122 131   0]
[115 119 130   0]
[117 120 132   0]
[122 124 133   0]
[ 71  90 110   0]
[67 80 97  0]
[123 124 133   0]
[117 120 1

[101 107 121   0]
[ 91 113 154   0]
[120 121 132   0]
[112 115 130   0]
[ 73  92 111   0]
[124 124 132   0]
[68 80 96  0]
[113 117 132   0]
[101 106 121   0]
[ 90 112 153   0]
[120 121 132   0]
[121 122 132   0]
[ 72  91 111   0]
[119 120 131   0]
[68 80 97  0]
[107 113 131   0]
[101 106 120   0]
[119 121 131   0]
[120 121 131   0]
[ 73  92 111   0]
[120 122 131   0]
[114 119 133   0]
[68 80 97  0]
[101 106 120   0]
[119 122 131   0]
[120 121 132   0]
[ 73  92 112   0]
[120 123 131   0]
[68 81 97  0]
[108 114 132   0]
[100 105 119   0]
[119 121 131   0]
[113 117 132   0]
[ 73  92 111   0]
[119 122 130   0]
[68 80 97  0]
[108 115 132   0]
[100 106 119   0]
[120 122 132   0]
[113 117 131   0]
[ 73  92 111   0]
[120 122 132   0]
[115 120 133   0]
[68 80 97  0]
[101 106 120   0]
[119 121 131   0]
[114 118 132   0]
[ 73  92 112   0]
[127 127 130   0]
[68 81 97  0]
[ 63  87 135   0]
[ 95 103 119   0]
[119 122 131   0]
[114 118 132   0]
[ 72  91 111   0]
[128 126 132   0]
[68 80 97  0]
[ 65  

[127 126 132   0]
[70 80 95  0]
[115 118 131   0]
[129 127 132   0]
[70 80 95  0]
[112 116 132   0]
[ 99 109 134   0]
[127 125 131   0]
[70 80 95  0]
[113 117 132   0]
[124 123 132   0]
[70 80 95  0]
[113 116 131   0]
[130 128 132   0]
[70 80 95  0]
[114 118 131   0]
[126 125 131   0]
[70 80 95  0]
[115 118 132   0]
[127 126 132   0]
[70 80 95  0]
[113 116 131   0]
[122 123 131   0]
[71 81 95  0]
[113 116 131   0]
[124 124 132   0]
[71 81 95  0]
[112 116 133   0]
[128 127 132   0]
[70 80 95  0]
[112 117 133   0]
[127 125 132   0]
[71 80 95  0]
[113 117 134   0]
[71 81 95  0]
[115 119 133   0]
[121 123 131   0]
[68 90 88  0]
[122 122 131   0]
[68 90 89  0]
[123 124 133   0]
[66 89 88  0]
[123 124 132   0]
[66 89 88  0]
[124 124 132   0]
[67 89 89  0]
[125 124 132   0]
[67 89 89  0]
[119 120 130   0]
[67 90 89  0]
[119 120 129   0]
[67 89 89  0]
[119 120 129   0]
[67 89 89  0]
[119 121 129   0]
[67 89 88  0]
[121 123 131   0]
[68 89 89  0]
[120 121 131   0]
[68 90 89  0]
[121 122 131   0

[81 87 88  0]
[ 72  98 149   0]
[ 95 115 157   0]
[113 117 132   0]
[74 80 81  0]
[ 68  96 149   0]
[ 95 116 157   0]
[123 123 133   0]
[81 87 87  0]
[ 69  96 148   0]
[ 95 116 157   0]
[122 123 133   0]
[81 87 88  0]
[ 69  95 148   0]
[ 95 116 157   0]
[116 119 131   0]
[81 87 87  0]
[ 72  98 149   0]
[ 95 115 157   0]
[117 121 132   0]
[ 68  95 148   0]
[ 94 114 156   0]
[124 125 133   0]
[80 86 86  0]
[ 67  94 148   0]
[ 93 114 156   0]
[116 120 133   0]
[ 94 115 156   0]
[118 121 133   0]
[ 95 115 156   0]
[112 116 131   0]
[ 95 115 156   0]
[112 116 130   0]
[ 94 115 157   0]
[121 123 131   0]
[ 67  94 149   0]
[ 94 115 157   0]
[121 122 131   0]
[ 97 118 158   0]
[ 94 115 156   0]
[114 118 131   0]
[83 89 90  0]
[ 93 114 156   0]
[115 119 132   0]
[62 71 80  0]
[ 95 116 157   0]
[116 119 133   0]
[62 72 81  0]
[116 119 132   0]
[62 72 81  0]
[117 119 132   0]
[82 88 89  0]
[122 122 132   0]
[117 120 132   0]
[82 88 89  0]
[129 127 134   0]
[119 121 132   0]
[82 88 89  0]
[128 126

[100 113 135   0]
[ 91 113 157   0]
[ 85 110 156   0]
[116 119 132   0]
[ 88 111 156   0]
[ 85 109 156   0]
[115 119 132   0]
[105 116 136   0]
[ 92 114 158   0]
[ 85 110 156   0]
[115 119 132   0]
[ 92 114 158   0]
[ 87 111 157   0]
[116 119 132   0]
[ 98 111 133   0]
[64 71 74  0]
[ 92 114 157   0]
[ 84 108 156   0]
[115 119 130   0]
[102 113 135   0]
[64 72 74  0]
[ 91 114 157   0]
[ 85 110 157   0]
[109 115 132   0]
[65 71 75  0]
[ 91 113 157   0]
[ 86 109 156   0]
[117 120 132   0]
[ 95 109 132   0]
[64 71 74  0]
[ 90 113 158   0]
[ 83 108 156   0]
[118 120 133   0]
[67 74 76  0]
[ 90 112 157   0]
[ 84 108 156   0]
[119 120 133   0]
[ 91 114 158   0]
[ 84 109 156   0]
[113 117 132   0]
[100 112 134   0]
[ 63  92 149   0]
[ 84 109 156   0]
[113 116 132   0]
[ 85 110 157   0]
[ 93 115 158   0]
[113 116 131   0]
[ 89 111 156   0]
[ 83 107 156   0]
[120 121 132   0]
[65 71 74  0]
[ 85 109 156   0]
[ 92 114 157   0]
[118 121 133   0]
[ 90 112 156   0]
[ 84 109 156   0]
[113 117 132   0

[ 92 113 154   0]
[103 110 113   0]
[ 92 113 155   0]
[101 108 113   0]
[ 91 113 155   0]
[103 110 114   0]
[ 91 113 154   0]
[103 109 113   0]
[ 93 114 155   0]
[102 109 113   0]
[ 93 114 154   0]
[103 109 113   0]
[ 93 114 154   0]
[102 109 112   0]
[ 93 114 156   0]
[101 108 112   0]
[ 91 113 155   0]
[101 108 113   0]
[ 91 113 155   0]
[101 108 112   0]
[ 94 115 157   0]
[ 98 105 109   0]
[ 89 111 155   0]
[ 99 106 110   0]
[ 92 113 155   0]
[ 97 104 108   0]
[ 93 114 155   0]
[ 90 112 154   0]
[ 90 112 155   0]
[ 69 101 160   0]
[ 69 102 158   0]
[ 67  85 114   0]
[ 69 103 163   0]
[ 68 100 158   0]
[ 71  88 117   0]
[ 74 104 159   0]
[ 67 100 158   0]
[ 19  60 140   0]
[ 68  99 156   0]
[ 74 104 159   0]
[ 67  99 158   0]
[ 19  60 140   0]
[ 72 101 155   0]
[ 73 103 160   0]
[ 66  99 159   0]
[ 20  61 140   0]
[ 69 100 155   0]
[ 73 103 159   0]
[ 67  99 157   0]
[ 21  62 141   0]
[ 70 100 155   0]
[ 72 102 159   0]
[ 66  99 158   0]
[ 18  60 139   0]
[ 71 101 156   0]
[ 75 104 1

[ 70 103 164   0]
[ 74 104 159   0]
[ 76 105 161   0]
[ 91 112 156   0]
[73 81 89  0]
[ 53  81 134   0]
[ 71 102 161   0]
[ 73 103 159   0]
[ 75 105 161   0]
[ 90 112 155   0]
[71 80 89  0]
[ 50  80 137   0]
[ 71 101 160   0]
[ 74 104 160   0]
[ 74 104 162   0]
[ 92 113 156   0]
[72 80 89  0]
[ 50  81 140   0]
[ 25  66 140   0]
[ 70 101 161   0]
[ 73 104 159   0]
[ 73 103 162   0]
[ 89 111 155   0]
[72 80 89  0]
[ 50  80 138   0]
[ 24  63 137   0]
[ 70 101 161   0]
[ 72 103 160   0]
[ 73 104 162   0]
[ 92 114 156   0]
[71 79 89  0]
[ 17  60 142   0]
[ 27  66 137   0]
[ 72 102 162   0]
[ 72 103 160   0]
[ 71 102 161   0]
[ 91 113 156   0]
[72 80 89  0]
[ 21  61 140   0]
[ 70 100 160   0]
[ 72 103 159   0]
[ 73 103 161   0]
[ 91 112 155   0]
[72 81 89  0]
[ 20  61 140   0]
[ 73 105 161   0]
[ 71 102 160   0]
[ 70 102 161   0]
[ 90 112 155   0]
[72 81 89  0]
[ 21  62 141   0]
[ 73 105 162   0]
[ 72 103 161   0]
[ 69 102 161   0]
[ 89 111 155   0]
[71 80 88  0]
[ 18  59 139   0]
[ 73 104 1

[ 81 106 154   0]
[ 89 112 156   0]
[128 126 132   0]
[ 66  94 150   0]
[ 92 115 157   0]
[ 71  97 150   0]
[ 92 114 157   0]
[ 70  97 150   0]
[ 91 113 157   0]
[112 135 172   0]
[ 69  96 149   0]
[ 64  92 148   0]
[107 131 170   0]
[ 69  96 149   0]
[ 90 113 156   0]
[121 140 170   0]
[ 74  99 150   0]
[ 92 114 157   0]
[142 154 174   0]
[ 73  99 150   0]
[ 89 112 156   0]
[108 131 170   0]
[ 69  96 149   0]
[ 91 113 156   0]
[111 133 171   0]
[ 73  98 150   0]
[ 90 113 157   0]
[115 136 171   0]
[ 72  98 150   0]
[ 93 115 158   0]
[136 151 173   0]
[ 65  93 148   0]
[ 89 112 157   0]
[141 155 175   0]
[ 67  94 148   0]
[ 93 115 158   0]
[115 138 173   0]
[ 70  96 149   0]
[ 91 113 158   0]
[115 137 170   0]
[ 70  96 150   0]
[ 90 113 157   0]
[139 153 172   0]
[ 69  96 150   0]
[ 89 113 157   0]
[111 134 170   0]
[ 68  95 150   0]
[ 89 112 157   0]
[184 187 190   0]
[108 130 169   0]
[ 71  97 150   0]
[ 91 113 157   0]
[189 192 196   0]
[111 132 170   0]
[ 71  98 150   0]
[ 91 113 1

[ 16  60 141   0]
[ 34  73 147   0]
[ 47  85 158   0]
[175 176 176   0]
[ 16  59 142   0]
[ 39  74 145   0]
[ 44  81 157   0]
[174 176 177   0]
[ 21  63 142   0]
[ 33  68 143   0]
[ 41  79 155   0]
[170 172 173   0]
[ 18  61 142   0]
[ 31  68 145   0]
[ 38  77 155   0]
[171 173 174   0]
[ 11  57 143   0]
[ 27  65 145   0]
[ 40  77 155   0]
[173 175 176   0]
[ 17  61 141   0]
[ 20  61 145   0]
[ 40  78 156   0]
[174 176 177   0]
[ 20  63 142   0]
[ 40  79 157   0]
[171 173 173   0]
[ 18  61 142   0]
[ 77  99 144   0]
[ 40  79 157   0]
[173 174 175   0]
[ 21  63 145   0]
[ 74  96 142   0]
[ 40  87 159   0]
[169 170 171   0]
[ 21  64 147   0]
[ 70  93 144   0]
[ 55  97 160   0]
[170 171 172   0]
[ 33  70 143   0]
[ 31  69 144   0]
[ 36  72 147   0]
[ 49  92 158   0]
[ 33  70 144   0]
[ 28  67 143   0]
[ 22  63 145   0]
[ 43  88 157   0]
[ 29  65 141   0]
[ 26  65 142   0]
[ 16  59 146   0]
[ 45  89 157   0]
[ 11  57 142   0]
[ 28  65 141   0]
[ 30  69 145   0]
[ 16  59 147   0]
[ 41  88 1

[ 17  64 153   0]
[ 19  66 154   0]
[ 34  90 151   0]
[ 44  97 154   0]
[ 49 105 159   0]
[ 36  77 167   0]
[ 36  74 165   0]
[ 37  75 163   0]
[ 80 104 144   0]
[ 15  62 152   0]
[ 16  64 155   0]
[ 32  90 153   0]
[ 45 100 156   0]
[ 42 100 154   0]
[ 34  76 168   0]
[ 35  75 166   0]
[ 42  78 164   0]
[ 14  61 152   0]
[ 17  65 156   0]
[ 32  92 155   0]
[ 43  98 155   0]
[ 54 107 163   0]
[ 32  74 168   0]
[ 40  78 165   0]
[ 43  79 164   0]
[ 82 106 144   0]
[ 13  60 152   0]
[ 20  67 155   0]
[ 29  87 147   0]
[ 41  96 152   0]
[ 54 105 159   0]
[ 36  78 169   0]
[ 36  75 166   0]
[ 42  79 165   0]
[ 82 104 141   0]
[ 18  65 156   0]
[ 17  65 155   0]
[ 29  88 151   0]
[ 40 106 170   0]
[ 54 105 160   0]
[ 32  75 168   0]
[ 35  74 165   0]
[ 42  79 164   0]
[67 78 89  0]
[ 82 105 140   0]
[ 16  64 155   0]
[ 16  65 155   0]
[ 28  87 149   0]
[ 40 102 166   0]
[ 50 109 170   0]
[ 36  79 170   0]
[ 33  72 164   0]
[ 39  76 163   0]
[ 81 103 137   0]
[ 15  62 153   0]
[ 20  67 153  

[ 34  87 174   0]
[ 12  68 173   0]
[ 21  65 152   0]
[ 37  98 153   0]
[ 25 113 186   0]
[ 41  98 151   0]
[ 54  87 164   0]
[ 34  88 162   0]
[ 51  87 161   0]
[147 151 152   0]
[ 33  85 171   0]
[ 12  68 172   0]
[ 23  65 150   0]
[ 31  95 152   0]
[ 24 111 185   0]
[ 50  86 167   0]
[ 32  83 157   0]
[ 33  81 155   0]
[146 149 150   0]
[ 35  87 172   0]
[ 12  68 173   0]
[ 36  98 153   0]
[ 21 111 184   0]
[ 46  84 165   0]
[ 31  85 160   0]
[ 52  87 162   0]
[ 30  80 156   0]
[ 35  87 172   0]
[ 11  68 172   0]
[ 34  96 153   0]
[ 48  84 164   0]
[ 35  90 163   0]
[ 31  81 157   0]
[ 34  85 170   0]
[ 11  68 171   0]
[ 31  95 152   0]
[ 51  86 161   0]
[ 32  84 158   0]
[ 35  86 170   0]
[ 11  68 171   0]
[ 26  65 144   0]
[ 40 101 156   0]
[ 49  82 160   0]
[ 33  84 158   0]
[ 32  84 170   0]
[ 12  68 170   0]
[ 26  65 145   0]
[ 41 102 158   0]
[ 57  90 161   0]
[ 33  83 159   0]
[ 35  87 171   0]
[ 12  68 171   0]
[ 22  62 143   0]
[ 27  94 153   0]
[ 52  87 161   0]
[ 35  83 1

[ 44 104 169   0]
[ 41  78 164   0]
[59 68 73  0]
[ 33 100 162   0]
[ 40  77 164   0]
[59 67 72  0]
[ 30  99 165   0]
[ 40  78 164   0]
[  8  74 170   0]
[ 42  78 165   0]
[59 68 73  0]
[ 41  78 165   0]
[ 43 102 163   0]
[ 44  79 165   0]
[59 68 72  0]
[ 42 102 164   0]
[ 42  78 165   0]
[128 126 130   0]
[59 68 72  0]
[ 44 103 165   0]
[ 43  79 164   0]
[128 125 127   0]
[59 67 71  0]
[ 44 104 165   0]
[ 42  78 164   0]
[130 127 129   0]
[ 41  78 165   0]
[128 125 128   0]
[ 39 100 162   0]
[ 38  75 165   0]
[ 41 102 163   0]
[ 41  77 165   0]
[  9  74 172   0]
[ 43 103 168   0]
[ 43  79 165   0]
[59 68 72  0]
[ 44 103 167   0]
[ 42  79 166   0]
[124 123 129   0]
[ 43 103 167   0]
[ 44  79 165   0]
[59 68 72  0]
[157 162 171   0]
[ 42  78 165   0]
[59 68 72  0]
[150 156 168   0]
[ 24  65 148   0]
[ 39 102 166   0]
[ 40  77 164   0]
[153 158 167   0]
[ 34 100 163   0]
[ 43  79 165   0]
[157 162 172   0]
[ 19  87 143   0]
[ 49  83 163   0]
[ 40  77 167   0]
[59 68 73  0]
[154 160 170  

[ 38  73 146   0]
[ 39  96 150   0]
[60 73 89  0]
[ 72  86 108   0]
[ 38  73 145   0]
[ 38  95 149   0]
[60 73 88  0]
[ 75  89 112   0]
[ 35  71 145   0]
[ 38  97 150   0]
[59 72 88  0]
[ 75  90 113   0]
[ 73 106 163   0]
[ 42  99 150   0]
[59 72 87  0]
[ 73  88 110   0]
[ 39  74 146   0]
[ 35  94 150   0]
[59 71 87  0]
[ 76  90 111   0]
[ 37  73 146   0]
[ 41  98 153   0]
[64 76 91  0]
[ 75  89 111   0]
[ 36  72 145   0]
[ 34  93 149   0]
[64 75 90  0]
[ 74  88 110   0]
[ 35  72 145   0]
[ 39  97 149   0]
[63 75 89  0]
[ 75  88 109   0]
[ 73 105 163   0]
[ 39  97 151   0]
[62 74 89  0]
[ 75  88 108   0]
[ 32  68 144   0]
[ 42  99 152   0]
[63 75 91  0]
[ 77  92 113   0]
[ 31  67 142   0]
[ 40  97 150   0]
[62 74 90  0]
[ 75  89 110   0]
[ 35  70 143   0]
[ 55 102 166   0]
[60 74 89  0]
[ 73  88 108   0]
[ 31  95 149   0]
[ 76 107 162   0]
[ 36  96 151   0]
[61 73 88  0]
[ 76  90 110   0]
[ 24  91 147   0]
[ 74 105 162   0]
[ 61 106 167   0]
[60 72 88  0]
[ 75  89 109   0]
[ 75 106 163

[ 35  71 148   0]
[153 156 156   0]
[ 33  70 148   0]
[151 154 155   0]
[ 32  69 147   0]
[152 155 156   0]
[ 31  69 146   0]
[164 167 167   0]
[ 30  68 145   0]
[165 168 168   0]
[ 29  67 145   0]
[164 167 168   0]
[ 28  67 145   0]
[155 158 159   0]
[ 27  66 145   0]
[154 157 158   0]
[ 28  67 145   0]
[154 157 158   0]
[ 33  70 147   0]
[154 158 159   0]
[ 32  70 147   0]
[155 158 159   0]
[ 32  70 146   0]
[154 158 159   0]
[ 31  69 147   0]
[155 158 159   0]
[ 31  69 146   0]
[156 159 160   0]
[ 31  69 147   0]
[155 158 159   0]
[ 31  68 147   0]
[168 171 171   0]
[ 32  70 148   0]
[167 170 171   0]
[ 32  70 149   0]
[154 158 158   0]
[ 29  67 147   0]
[157 160 160   0]
[ 31  69 148   0]
[156 160 160   0]
[ 33  71 149   0]
[157 160 160   0]
[ 33  71 148   0]
[154 158 158   0]
[ 36  72 148   0]
[157 159 160   0]
[ 40  76 150   0]
[167 170 170   0]
[ 46  79 146   0]
[155 157 158   0]
[ 52  82 145   0]
[164 167 168   0]
[ 55  84 146   0]
[152 155 156   0]
[ 57  86 146   0]
[151 154 1

[ 73 105 164   0]
[ 72 103 160   0]
[56 72 95  0]
[ 72 103 161   0]
[ 75 107 164   0]
[60 75 95  0]
[ 74 106 164   0]
[ 76 106 162   0]
[55 71 93  0]
[ 72 105 163   0]
[ 76 106 161   0]
[54 69 91  0]
[ 35  71 145   0]
[ 75 105 161   0]
[58 74 95  0]
[ 72 105 164   0]
[ 71 103 161   0]
[59 75 98  0]
[ 75 106 163   0]
[ 72 104 161   0]
[58 74 94  0]
[ 73 105 163   0]
[ 71 103 162   0]
[57 72 94  0]
[ 71 104 163   0]
[ 73 103 160   0]
[58 73 96  0]
[ 34  71 145   0]
[ 71 103 162   0]
[57 71 91  0]
[ 33  69 145   0]
[ 71 103 161   0]
[56 71 93  0]
[ 74 105 163   0]
[ 73 105 162   0]
[54 68 89  0]
[ 76 107 164   0]
[ 73 105 161   0]
[62 76 96  0]
[ 35  71 144   0]
[ 72 104 161   0]
[55 71 92  0]
[ 34  69 143   0]
[ 72 104 162   0]
[58 73 95  0]
[ 73 105 163   0]
[ 70 102 160   0]
[59 73 93  0]
[ 74 106 163   0]
[ 72 103 160   0]
[62 76 96  0]
[ 73 105 163   0]
[ 72 103 161   0]
[59 73 93  0]
[ 73 104 161   0]
[ 75 107 164   0]
[59 74 94  0]
[ 71 102 159   0]
[ 75 106 164   0]
[58 74 94  0]


[ 18  63 150   0]
[ 33  74 154   0]
[ 42  78 165   0]
[137 140 141   0]
[ 18  64 152   0]
[ 28  72 155   0]
[ 38  77 166   0]
[137 141 142   0]
[ 17  63 150   0]
[ 26  70 155   0]
[ 36  76 165   0]
[133 137 138   0]
[ 22  68 154   0]
[ 22  67 154   0]
[ 44  98 157   0]
[ 42  79 166   0]
[140 144 146   0]
[ 13  60 149   0]
[ 18  64 153   0]
[ 17  65 155   0]
[ 44  97 155   0]
[ 38  75 163   0]
[135 139 141   0]
[ 19  65 151   0]
[ 16  64 154   0]
[ 15  64 155   0]
[ 45 100 157   0]
[ 36  74 163   0]
[141 145 147   0]
[ 21  68 153   0]
[ 16  65 156   0]
[ 17  65 155   0]
[ 44  99 157   0]
[ 35  73 164   0]
[141 145 148   0]
[ 18  67 156   0]
[ 22  69 156   0]
[ 43  98 156   0]
[ 39  77 165   0]
[140 144 147   0]
[ 14  62 152   0]
[ 17  64 154   0]
[ 42  96 155   0]
[ 37  77 165   0]
[145 149 152   0]
[ 14  62 153   0]
[ 15  64 154   0]
[ 42  97 156   0]
[ 34  73 165   0]
[142 146 150   0]
[ 31  79 165   0]
[ 17  65 155   0]
[ 43  98 156   0]
[ 36  75 165   0]
[145 150 154   0]
[ 32  80 1

[72 82 79  0]
[159 161 162   0]
[72 82 79  0]
[159 162 163   0]
[159 162 162   0]
[71 81 79  0]
[160 163 164   0]
[71 81 79  0]
[160 163 164   0]
[71 81 79  0]
[160 163 164   0]
[160 162 164   0]
[71 81 79  0]
[150 153 154   0]
[71 82 79  0]
[150 153 154   0]
[72 82 79  0]
[161 163 164   0]
[71 81 79  0]
[164 166 167   0]
[164 166 168   0]
[151 154 155   0]
[72 81 79  0]
[152 155 157   0]
[163 166 168   0]
[71 81 78  0]
[164 167 169   0]
[72 81 79  0]
[153 156 158   0]
[71 81 78  0]
[ 65  86 134   0]
[154 157 159   0]
[71 81 79  0]
[167 169 171   0]
[72 81 79  0]
[167 169 171   0]
[72 81 79  0]
[158 160 162   0]
[72 81 80  0]
[159 161 163   0]
[159 161 163   0]
[72 81 80  0]
[160 162 164   0]
[72 81 79  0]
[161 163 165   0]
[72 81 80  0]
[161 163 165   0]
[72 81 79  0]
[161 164 165   0]
[73 81 80  0]
[153 156 158   0]
[72 81 80  0]
[152 155 157   0]
[162 165 167   0]
[72 81 80  0]
[163 166 168   0]
[164 167 168   0]
[156 159 160   0]
[158 161 162   0]
[158 161 162   0]
[164 167 169   0

[175 177 178   0]
[176 177 178   0]
[177 178 179   0]
[169 171 172   0]
[ 12  85 141   0]
[169 171 172   0]
[ 11  82 139   0]
[170 172 173   0]
[170 172 173   0]
[171 173 174   0]
[169 172 172   0]
[178 180 181   0]
[179 181 182   0]
[170 173 174   0]
[152 157 166   0]
[172 174 175   0]
[ 61  82 131   0]
[173 174 175   0]
[ 12  57 127   0]
[ 66  84 129   0]
[175 176 177   0]
[175 176 177   0]
[175 176 177   0]
[169 171 172   0]
[169 171 172   0]
[163 165 166   0]
[171 173 173   0]
[172 174 175   0]
[166 168 169   0]
[165 167 168   0]
[173 175 175   0]
[173 175 176   0]
[168 169 170   0]
[169 171 171   0]
[168 170 171   0]
[170 171 172   0]
[170 171 172   0]
[171 172 172   0]
[172 173 174   0]
[173 175 175   0]
[168 170 170   0]
[175 176 176   0]
[170 171 172   0]
[169 171 172   0]
[171 172 173   0]
[172 174 175   0]
[167 168 169   0]
[173 175 176   0]
[169 171 172   0]
[169 171 172   0]
[171 173 174   0]
[172 174 175   0]
[168 171 171   0]
[171 173 173   0]
[171 173 173   0]
[171 173 1

error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
